const r = require('express').Router();
const c = require('../controllers/driverController');
const { authenticate, authorize } = require('../middleware/auth');
r.use(authenticate, authorize('admin'));
r.get('/', c.list);
r.get('/:id', c.get);
r.post('/', c.create);
r.put('/:id', c.update);
r.delete('/:id', c.remove);
module.exports = r;
